import Head from "next/head";
import type { NextPageWithLayout } from './_app'
import type { ReactElement } from 'react'
import Layout from "components/Layout/Layout";

const Home: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>CryptoPunk Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/521ef297f0.js" crossOrigin="anonymous" async />
      </Head>

      <p>Hello World<i className="fa-solid fa-thumbs-up fa-5x"></i></p>
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}

export default Home;
