import Head from "next/head";
import type { NextPageWithLayout } from './_app'
import { ReactElement, useEffect, useRef, useState } from 'react'
import Layout from "components/Layout/Layout";
import { getNFTs } from "utils/utils";
import {
  Container,
  SimpleGrid,
} from '@chakra-ui/react'
import NFT from "components/NFT/NFT";
import InfiniteScroll from "react-infinite-scroll-component";

const Home: NextPageWithLayout = () => {

  const [nftList, setNftList] = useState<NFTItem[]>([])

  useEffect(() => {
    getMoreNFTs()
  }, [])

  const getMoreNFTs = async () => {
    let moreList = await getNFTs()
    let tmp = nftList.map(nft => nft)
    moreList.forEach(nft => {
      tmp.push(nft)
    })
    setNftList(tmp)
  }

  return (
    <Container
      maxW={{
        sm: "container.sm",
        md: "container.md",
        lg: "container.lg",
        xl: "container.xl",
      }}
      paddingTop={'66px'}
      paddingBottom={'66px'}
    >
      <Head>
        <title>CryptoPunk Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/521ef297f0.js" crossOrigin="anonymous" async />
      </Head>
      <InfiniteScroll
        dataLength={nftList.length}
        next={getMoreNFTs}
        hasMore={true}
        loader={<h4>Loading...</h4>}
      >
        <SimpleGrid
          columns={[1, 2, 2, 3, 4]}
          spacing={6}
        >
          {
            nftList.map((item, index) => (
              <NFT item={item} key={index} />
            ))
          }
        </SimpleGrid>
      </InfiniteScroll>
      
    </Container>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}

export default Home;
