import Head from "next/head";
import type { NextPageWithLayout } from "./_app";
import { ReactElement, useEffect, useRef, useState } from "react";
import Layout from "components/Layout/Layout";
import { getNFTs } from "utils/utils";
import { Container, SimpleGrid } from "@chakra-ui/react";
import NFT from "components/NFT/NFT";
import InfiniteScroll from "react-infinite-scroll-component";
import NFTModal from "components/NFTModal/NFTModal";

const Home: NextPageWithLayout = () => {
  const [nftList, setNftList] = useState<NFTItem[]>([]);
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
  const [selectedItem, setSelectedItem] = useState<NFTItem>({
    amount: 0,
    block_number_minted: 0,
    metadata: {},
    name: "",
    symbol: "",
    token_address: "",
    token_hash: "",
    token_id: 0,
    token_uri: "",
  });

  useEffect(() => {
    getMoreNFTs();
  }, []);

  const getMoreNFTs = async () => {
    let moreList = await getNFTs();
    let tmp = nftList.map((nft) => nft);
    moreList.forEach((nft) => {
      tmp.push(nft);
    });
    setNftList(tmp);
  };

  const handleNFTClick = (index: number) => {
    setSelectedItem(nftList[index]);
    setIsModalOpen(true)
  };

  return (
    <Container
      maxW={{
        sm: "container.sm",
        md: "container.md",
        lg: "container.lg",
        xl: "container.xl",
      }}
      paddingTop={"66px"}
      paddingBottom={"66px"}
    >
      <Head>
        <title>CryptoPunk Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://kit.fontawesome.com/521ef297f0.js"
          crossOrigin="anonymous"
          async
        />
      </Head>
      <InfiniteScroll
        dataLength={nftList.length}
        next={getMoreNFTs}
        hasMore={true}
        loader={<h4>Loading...</h4>}
      >
        <SimpleGrid columns={[1, 2, 2, 3, 4]} spacing={6}>
          {nftList.map((item, index) => (
            <NFT
              item={item}
              key={index}
              onClick={() => handleNFTClick(index)}
            />
          ))}
        </SimpleGrid>
      </InfiniteScroll>

      <NFTModal
        item={selectedItem}
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
      />
    </Container>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
